### ISSUE TITLE
Select not working

### ISSUE THREAD

**Issue by techie244** [rapsacnz/MultiSelect#1]

**Comment by rapsacnz** [comment]
Can't fix it if you don't give me details - console messages, lightning messages, how to reproduce

**Comment by techie244** [comment]
It doesn't select and the return the selected value.Basically i doesnt respond if an option is selected

**Comment by rapsacnz** [comment]
Have you inspected the component on the console? Any errors. I still can't fix it if you can't provide me with a reproducible error. In this that might include a small component that demonstrates the error reliably.

**Comment by techie244** [comment]
![image](https://cloud.githubusercontent.com/assets/20929582/25542884/01b9ca84-2c72-11e7-8c69-29c2fd5aec22.png)

Yes i have inspected no error in console.log
attaching screenshot shows no value is added to drop down

**Comment by rapsacnz** [comment]
How are you adding selectoptions to your select?
I add the options (which are often derived via a query). If you have bound to a list of options, after you change that list, you need to call `reinit()` - eg:

    component.set("v.options",optionsFromQuery);
    component.find("selectComponent").reInit();

**Comment by techie244** [comment]
Thanks , Will try that 
Can you please let me know how would i get value in optionsFromQuery ,
do you have a sample code for it

**Comment by ankitbaranwal26** [comment]
Hi, thanks for sharing this. The drop down is blank on initial page load. How do we populate the values initially. I tried using init handler method to populate the "options" attribute but does not work. Can you help?

**Comment by rapsacnz** [comment]
Can you show your code? Both the enclosing code and any mods you have made this code?

**Comment by rapsacnz** [comment]
I'm closing this - I know that this feature works, so it's simply an implementation issue. If you find something wrong, please submit a pull request.

**Comment by anshsetia1818** [comment]
Hi I just tried to use your solution " https://github.com/rapsacnz/MultiSelect" but it is giving error 
"An internal server error has occurred
Error ID: 479439401-113768 (-1175146990)"
I think it's either incomplete or some file is missing.
